services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datawow
      MYSQL_USER: datawow
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
