import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { Toaster } from "@/components/alert/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen overflow-hidden">
      <body className="flex h-screen overflow-hidden bg-gray-50">
        <aside className="h-full sticky top-0">
          <Navbar />
        </aside>
        <div className="m-6 bg-white h-full w-full rounded-2xl overflow-scroll">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
